insert into DEPARTMENTS values (10, 'Administration');
insert into DEPARTMENTS values (20, 'Marketing');
insert into DEPARTMENTS values (30, 'Purchasing');
insert into DEPARTMENTS values (40, 'Human Resources');
insert into DEPARTMENTS values (50, 'Shipping');
insert into DEPARTMENTS values (60, 'IT');
insert into DEPARTMENTS values (70, 'Public Relations');
insert into DEPARTMENTS values (80, 'Sales');
insert into DEPARTMENTS values (90, 'Executive');
insert into DEPARTMENTS values (100, 'Finance');
insert into DEPARTMENTS values (110, 'Accounting');
insert into DEPARTMENTS values (120, 'Treasury');
insert into DEPARTMENTS values (130, 'Corporate Tax');
insert into DEPARTMENTS values (140, 'Control And Credit');
insert into DEPARTMENTS values (150, 'Shareholder Services');
insert into DEPARTMENTS values (160, 'Benefits');
insert into DEPARTMENTS values (170, 'Manufacturing');
insert into DEPARTMENTS values (180, 'Construction');
insert into DEPARTMENTS values (190, 'Contracting');
insert into DEPARTMENTS values (200, 'Operations');
insert into DEPARTMENTS values (210, 'IT Support');
insert into DEPARTMENTS values (220, 'NOC');
insert into DEPARTMENTS values (230, 'IT Helpdesk');
insert into DEPARTMENTS values (240, 'Government Sales');
insert into DEPARTMENTS values (250, 'Retail Sales');
insert into DEPARTMENTS values (260, 'Recruiting');
insert into DEPARTMENTS values (270, 'Department Updated Value');
